version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV}
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    ports:
      - '3000:3000'
    depends_on:
      - postgres

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV}
        - REACT_APP_API_URL=${REACT_APP_API_URL} 
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    ports:
      - '8080:80'
    depends_on:
      - server

volumes:
  pgdata:
